import React from 'react';
import type { Metadata } from 'next';
import { Inter, Nunito } from 'next/font/google';

import './globals.css';

export const metadata: Metadata = {
  title: 'Collab Task Hub',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-inter',
});

const nunito = Nunito({
  subsets: ['latin', 'cyrillic'],
  variable: '--font-nunito',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${nunito.variable}`}>
      <body>{children}</body>
    </html>
  );
}
